ARDUINO_DIR  = /usr/share/arduino

TARGET       = SPI02
ARDUINO_LIBS = SPI

MCU          = atmega328p
F_CPU        = 16000000
ARDUINO_PORT = /dev/ttyUSB0

include /usr/share/arduino/Arduino.mk

#    AVR_TOOLS_PATH = /usr/bin
# AVRDUDE_CONF   = /etc/avrdude.conf
AVRDUDE_ARD_BAUDRATE = 57600
# AVRDUDE_ARD_EXTRAOPTS = -vvvv
