ARDUINO_DIR  = /usr/share/arduino
BOARD_TAG    = atmega328
TARGET       = buttons01
ARDUINO_LIBS = 

#MCU          = atmega328p
#F_CPU        = 16000000
ARDUINO_PORT = /dev/ttyUSB0

include /home/luiz/src/arduino/Arduino.mk

# AVR_TOOLS_PATH = /usr/bin
# AVRDUDE_CONF   = /etc/avrdude.conf
# AVRDUDE_ARD_BAUDRATE = 57600
# AVRDUDE_ARD_EXTRAOPTS = -vvvv
